package com.example.backstreet_cycles.data.repository

import android.app.Application
import com.example.backstreet_cycles.domain.model.dto.Locations
import com.mapbox.api.directions.v5.models.DirectionsRoute
import com.mapbox.geojson.Point
import com.mapbox.maps.MapboxMap
import com.mapbox.maps.plugin.locationcomponent.OnIndicatorPositionChangedListener
import com.mapbox.navigation.core.MapboxNavigation
import com.mapbox.navigation.ui.maps.location.NavigationLocationProvider
import com.mapbox.navigation.ui.maps.route.line.api.MapboxRouteLineApi
import com.mapbox.navigation.ui.maps.route.line.api.MapboxRouteLineView
import com.mapbox.navigation.ui.maps.route.line.model.RouteLineColorResources
import com.mapbox.navigation.ui.maps.route.line.model.RouteLineResources

abstract class MapRepository(private val application: Application)
{
    companion object
    {
        var currentRoute = mutableListOf<DirectionsRoute>()
        val distances = mutableListOf<Double>()
        val durations = mutableListOf<Double>()
        val wayPoints = mutableListOf<Point>()
        var location = mutableListOf<Locations>()
    }

    /**
     * [NavigationLocationProvider] is a utility class that helps to provide location updates generated by the Navigation SDK
     * to the Maps SDK in order to update the user location indicator on the map.
     */
    protected val navigationLocationProvider = NavigationLocationProvider()
}